name: colok
description: A color picker.
publish_to: 'none'
version: 2.3.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSC-VF.ttf